### ISSUE TITLE
Cannot start service nginx

### ISSUE THREAD

**Issue by Pratham0x01** [mpast/mobileAudit#10]
ERROR: for mobileaudit_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint mobileaudit_nginx_1 (b2fc27f48babbe003703af1afddba6c3a0e673e2836aca4e86f786b0a0bae0f8): Bind for 0.0.0.0:443 failed: port is already allocated

**Comment by mpast** [comment]
Hi, is this the first time you are executing the application? If so, maybe you have other application running in that port, try to change the port in `docker-compose.yaml` for a new one:

```yaml
ports:
      - "8888:8888"
      - "443:443" <--
```
On the other hand, if you have previously executed the app, maybe the containers are still running, to stop them execute `docker-compose down` and then try again `docker-compose up`.
