### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by mpast** [mpast/mobileAudit#103]
Some user have been reported 500 errors

**Comment by f0xp1t** [comment]
Hey tried the patch , rebuilt the docker image but still same error , i am adding the log file again , appreciate your assistance.
[log_patched_version.txt](https://github.com/mpast/mobileAudit/files/13608538/log_patched_version.txt)

Seems Permission issues 
rabbitmq_1  | 2023-12-08 03:23:05.082810+00:00 [error] <0.229.0> BOOT FAILED
rabbitmq_1  | 2023-12-08 03:23:05.082810+00:00 [error] <0.229.0> ===========
rabbitmq_1  | 2023-12-08 03:23:05.082810+00:00 [error] <0.229.0> failed to open log file at '/var/log/rabbitmq/rabbit@8ba761dc19dc_upgrade.log', reason: permission denied
rabbitmq_1  | 2023-12-08 03:23:05.082810+00:00 [error] <0.229.0>


then another error worker_1    | [2023-12-08 04:23:06,137: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq:5672//: [Errno 111] Connection refused.

**Comment by f0xp1t** [comment]
lol i correct Myself ...it worked after a few retries .....

![image](https://github.com/mpast/mobileAudit/assets/153251075/60380c1b-4fd9-4700-ad41-e54a811d7ed7)

db_1        | 2023-12-08 03:28:28.584 UTC [22] LOG:  checkpoint complete: wrote 275 buffers (1.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=27.333 s, sync=0.039 s, total=27.399 s; sync files=107, longest=0.007 s, average=0.001 s; distance=1648 kB, estimate=1648 kB
worker_1    | [2023-12-08 04:28:46,726: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq:5672//: [Errno -3] Temporary failure in name resolution.
worker_1    | Trying again in 32.00 seconds... (16/100)

After trying to upload the APK i am getting the following:

![image](https://github.com/mpast/mobileAudit/assets/153251075/bd1011b9-6c37-4eb9-b435-11ec7f570aea)

cket.gaierror: [Errno -3] Temporary failure in name resolution
web_1       |
web_1       | The above exception was the direct cause of the following exception:
web_1       |
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1       |     response = get_response(request)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1       |   File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
web_1       |     return func(*args, **kwds)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
web_1       |     return view_func(request, *args, **kwargs)
web_1       |   File "/app/./app/views.py", line 182, in create_scan
web_1       |     task_id = task_create_scan.delay(scan.id)
web_1       |   File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 425, in delay
web_1       |     return self.apply_async(args, kwargs)
web_1       |   File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 575, in apply_async
web_1       |     return app.send_task(
web_1       |   File "/usr/local/lib/python3.9/site-packages/celery/app/base.py", line 788, in send_task
web_1       |     amqp.send_task_message(P, name, message, **options)
web_1       |   File "/usr/local/lib/python3.9/site-packages/celery/app/amqp.py", line 510, in send_task_message
web_1       |     ret = producer.publish(
web_1       |   File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 186, in publish
web_1       |     return _publish(
web_1       |   File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 556, in _ensured
web_1       |     return fun(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 195, in _publish
web_1       |     channel = self.channel
web_1       |   File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 218, in _get_channel
web_1       |     channel = self._channel = channel()
web_1       |   File "/usr/local/lib/python3.9/site-packages/kombu/utils/functional.py", line 34, in __call__
web_1       |     value = self.__value__ = self.__contract__()
web_1       |   File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 234, in <lambda>
web_1       |     channel = ChannelPromise(lambda: connection.default_channel)
web_1       |   File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 953, in default_channel
web_1       |     self._ensure_connection(**conn_opts)
web_1       |   File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 459, in _ensure_connection
web_1       |     return retry_over_time(
web_1       |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
web_1       |     self.gen.throw(typ, value, traceback)
web_1       |   File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
web_1       |     raise ConnectionError(str(exc)) from exc
web_1       | kombu.exceptions.OperationalError: [Errno -3] Temporary failure in name resolution
web_1       | [pid: 13|app: 0|req: 9/14] 172.21.0.4 () {54 vars in 1056 bytes} [Fri Dec  8 04:37:01 2023] POST /scan/create/1 => generated 145 bytes in 5002 msecs (HTTP/1.0 500) 7 headers in 217 bytes (1 switches on core 0)
worker_1    | [2023-12-08 04:37:27,247: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq:5672//: [Errno -3] Temporary failure in name resolution.
worker_1    | Trying again in 32.00 seconds... (16/100)
