### ISSUE TITLE
Unable to configure handler 'logfile'

### ISSUE THREAD

**Issue by SecLoop** [mpast/mobileAudit#40]
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python3.9/logging/config.py", line 564, in configure
worker_1    |     handler = self.configure_handler(handlers[name])
worker_1    |   File "/usr/local/lib/python3.9/logging/config.py", line 745, in configure_handler
worker_1    |     result = factory(**kwargs)
worker_1    |   File "/usr/local/lib/python3.9/logging/__init__.py", line 1146, in __init__
worker_1    |     StreamHandler.__init__(self, self._open())
worker_1    |   File "/usr/local/lib/python3.9/logging/__init__.py", line 1175, in _open
worker_1    |     return open(self.baseFilename, self.mode, encoding=self.encoding,
worker_1    | FileNotFoundError: [Errno 2] No such file or directory: '/app/app/logs/debug.log'
worker_1    | 
worker_1    | The above exception was the direct cause of the following exception:
worker_1    | 
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/bin/celery", line 8, in <module>
worker_1    |     sys.exit(main())
worker_1    |   File "/usr/local/lib/python3.9/site-packages/celery/__main__.py", line 15, in main
worker_1    |     sys.exit(_main())
worker_1    |   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 213, in main
worker_1    |     return celery(auto_envvar_prefix="CELERY")
worker_1    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
worker_1    |     return self.main(*args, **kwargs)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
worker_1    |     rv = self.invoke(ctx)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
worker_1    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
worker_1    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
worker_1    |     return ctx.invoke(self.callback, **ctx.params)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
worker_1    |     return callback(*args, **kwargs)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
worker_1    |     return f(get_current_context(), *args, **kwargs)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/celery/bin/base.py", line 132, in caller
worker_1    |     return f(ctx, *args, **kwargs)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/celery/bin/worker.py", line 320, in worker
worker_1    |     worker = app.Worker(
worker_1    |   File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 94, in __init__
worker_1    |     self.app.loader.init_worker()
worker_1    |   File "/usr/local/lib/python3.9/site-packages/celery/loaders/base.py", line 111, in init_worker
worker_1    |     self.import_default_modules()
worker_1    |   File "/usr/local/lib/python3.9/site-packages/celery/loaders/base.py", line 105, in import_default_modules
worker_1    |     raise response
worker_1    |   File "/usr/local/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 276, in send
worker_1    |     response = receiver(signal=self, sender=sender, **named)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/celery/fixups/django.py", line 82, in on_import_modules
worker_1    |     self.worker_fixup.validate_models()
worker_1    |   File "/usr/local/lib/python3.9/site-packages/celery/fixups/django.py", line 120, in validate_models
worker_1    |     self.django_setup()
worker_1    |   File "/usr/local/lib/python3.9/site-packages/celery/fixups/django.py", line 116, in django_setup
worker_1    |     django.setup()
worker_1    |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
worker_1    |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/django/utils/log.py", line 75, in configure_logging
worker_1    |     logging_config_func(logging_settings)
worker_1    |   File "/usr/local/lib/python3.9/logging/config.py", line 809, in dictConfig
worker_1    |     dictConfigClass(config).configure()
worker_1    |   File "/usr/local/lib/python3.9/logging/config.py", line 571, in configure
worker_1    |     raise ValueError('Unable to configure handler '
worker_1    | ValueError: Unable to configure handler 'logfile'

![image](https://user-images.githubusercontent.com/15940596/129999716-e39b7cd3-cc4a-4a06-81cc-5cce7b22a371.png)

**Comment by SecLoop** [comment]
use docker-compse

**Comment by mpast** [comment]
Hi @SecLoop, did you do `docker-compose build` and then `docker-compose up`?

**Comment by SecLoop** [comment]
Yes, I did

**Comment by mpast** [comment]
It seems is not finding the` /app/app/logs/debug.log` file, although it should be created on the `docker-compose build` command, could you confirm if the file is present? if not, could you provide some technical details about the host and docker version? Thanks a lot
![image](https://user-images.githubusercontent.com/9053588/130818399-a4b05fda-c9a3-4957-8f00-bfaf72992a10.png)

**Comment by SecLoop** [comment]
system versions
Linux CentosScan 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

docker versions
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:49 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:54:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Comment by mpast** [comment]
Thanks for all the specs, is the `/app/logs/debug.log` file present in the folder of the repository?

**Comment by SecLoop** [comment]
CentOS doesn't have that directory  /app/logs/debug.log

Unable to enter docker container

![image](https://user-images.githubusercontent.com/15940596/131940250-c525b68f-d652-4c23-9091-f196b697d886.png)

**Comment by mpast** [comment]
Hi,
could you try to do a docker-compose down and do the build and up again? if that’s not working, from the host do a 
`
mkdir app/logs;
touch app/logs/debug.log
`
and then do the up again,
thanks

**Comment by SecLoop** [comment]
mac big sur 11.5.2
```
$ docker-compose up -d
[+] Running 3/4
 ⠿ Container mobileaudit_db_1        Recreated                                                                                                                                                                                                           0.1s
 ⠿ Container mobileaudit_web_1       Recreated                                                                                                                                                                                                           0.1s
 ⠹ Container mobileaudit_rabbitmq_1  Creating                                                                                                                                                                                                            0.1s
 ⠿ Container mobileaudit_nginx_1     Recreated                                                                                                                                                                                                           0.1s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/xxxxxx/mobileAudit/rabbitmq/logs
```
Treatment method

Manual creation required

**Comment by SecLoop** [comment]
Thank you very much for sharing
