### ISSUE TITLE
install minor question

### ISSUE THREAD

**Issue by SecLoop** [mpast/mobileAudit#41]
```
#15 208.2 WARNING: You are using pip version 21.0.1; however, version 21.2.4 is available.
#15 208.2 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c pip install -r requirements.txt]: exit code: 2
```
modify

# Install python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

Network reasons

Chinese users pull and update the user system slowly. Can you customize the image source

**Comment by mpast** [comment]
Hi SecLoop,
I'll update the python version and dependencies and add this change into the Dockerfile, 
Thanks a lot for the recommendation,
Monica
