### ISSUE TITLE
Error after running docker-compose up

### ISSUE THREAD

**Issue by a2t2** [mpast/mobileAudit#45]
Testing on Ubuntu 20.04 in VMWare Fusion.

Followed docker and docker-compse setup in:
https://web.archive.org/web/20210911111022/https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04 (step 1 and 2)
https://web.archive.org/web/20210825112220/https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-20-04. (step 1)

git cloned the repo. In the project folder, docker-compose build results in the following:

![image](https://user-images.githubusercontent.com/8272456/135363045-d05df6ec-41ea-4239-9895-7d21be684940.png)

docker-compose up:

![image](https://user-images.githubusercontent.com/8272456/135363122-e445a19c-1d3f-4983-92f1-b18dbd625a19.png)

Any suggestion on how to resolve this issue ? Thank you.

**Comment by mpast** [comment]
Hi @a2t2,
In the new version of the rabbitmq there are some permission problems because the volume is being created with only root permissions, so I have downgraded the version until that is resolved,
Please, could you confirm that the issue is fixed with this new version?
Thanks a lot,
Monica

**Comment by a2t2** [comment]
It works now. Thanks @mpast.
