### ISSUE TITLE
docker compose up / docker-compose build

### ISSUE THREAD

**Issue by baseloo** [mpast/mobileAudit#48]
after cloning the project, tried to execute the command :
**docker-compose build**

Got the following error 
unexpected character "." in variable name near "app localhost 127.0.0.1\nENV=PROD\nSQL_ENGINE=django.db.backends.postgresql\nSQL_DATABASE=postgres\nSQL_USER=postgres\nSQL_PASSWORD=postgres\nSQL_HOST=db\nSQL_PORT=5432\nLANG=en_US.UTF-8\nCWE_URL=https://cwe.mitre.org/data/definitions/\nDEFECTDOJO_URL=http://defectdojo:8080/finding/\nDEFECTDOJO_API_URL=http://defectdojo:8080/api/v2/\nDEFECTDOJO_API_KEY=DEFECTDOJO_API_KEY\nDEFECTDOJO_ENABLED=False\nMALWARE_ENABLED=False\nMALWAREDB_URL=https://www.malwaredomainlist.com/mdlcsv.php\nMALTRAILDB_URL=https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt\nVIRUSTOTAL_ENABLED=False\nVIRUSTOTAL_URL=https://www.virustotal.com/\nVIRUSTOTAL_FILE_URL=https://www.virustotal.com/gui/file/\nVIRUSTOTAL_API_URL_V3=https://www.virustotal.com/api/v3/\nVIRUSTOTAL_API_URL_V2=https://www.virustotal.com/vtapi/v2/\nVIRUSTOTAL_API_KEY=VIRUSTOTAL_API_KEY\nVIRUSTOTAL_UPLOAD=False\nRABBITMQ_DEFAULT_USER=guest\nRABBITMQ_DEFAULT_PASS=guest\nCELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672\nCELERY_RESULT_BACKEND=db+sqlite:///rabbitmq/results.sqlite\n"

Then I have tried to edit .env.example by removing 127.0.01 and got the following error:
key cannot contain a space

Do you have any suggestions please?

**Comment by mpast** [comment]
Hi, 
Docker-compose had a breaking change that leads to problems in the parsing of environment variables, I'll work to change the example file to avoid this problem.
https://docs.docker.com/compose/cli-command/

In the meantime, you can use new command
`docker compose`

or

disable compose v2
`docker-compose disable-v2`

Thanks a lot for reporting to me,
Monica

**Comment by mpast** [comment]
Hi @baseloo,
Could you confirm that with the fix in PR #49 the docker-compose build is working as intended?
Thanks again,
Monica

**Comment by baseloo** [comment]
Thank you @mpast the above problems fixed.
