### ISSUE TITLE
Added report generation and export function

### ISSUE THREAD

**Issue by firmianay** [mpast/mobileAudit#60]
Hi, useful project!

1. It would be great if there was a report generation and export function.
2. Is it possible to remove the cumbersome login authentication function and only generate a random token as api authentication at startup, which is more conducive to the automation process

thanks

**Comment by mpast** [comment]
Hi @firmianay, 
First, I would like to thank you for your kind words and feedback, I really appreciate it,
For the first request, what kind of export were you thinking about? For now, you can export a pdf with the results of a scan, would you like other specifically?
And about the second one, I think it would be a great idea, I would take notes on that and try to figure out how to implement that,
Thanks again for the feedback!

**Comment by firmianay** [comment]
thanks for your reply,
Yes I saw the pdf download function in the web interface, I wrote a [batch analysis script](https://github.com/firmianay/Vehicle-Security-Toolkit/blob/main/apk-audit.py) that supports automatic registration, login and upload scanning, but pdf download needs to provide session, it will be more convenient if api interface can be provided

**Comment by mpast** [comment]
Hi @firmianay,
That script and the whole toolkit seems so cool, I'll have a look and see what I can do to improve this process and implement those suggestions,
Thanks a lot for all your work!
