### ISSUE TITLE
Requested API level 32 is larger than maximum we have, returning API level 28 instead.

### ISSUE THREAD

**Issue by julienkermarec** [mpast/mobileAudit#88]
Hello,

When i create a new scan with a recent APK, scan is frozen at 20%, status decompiling, and i see this message error in the console : 
Requested API level 32 is larger than maximum we have, returning API level 28 instead.

Do you have a solution for API 29+ ?

**Comment by mpast** [comment]
Hi @julienkermarec,
First, thanks for the report but I am not able to replicate the issue
Is there any other error in the logs after this?, For me, every apk that has API 29+ it shows that debug log but then it continues the decompilation and findings gathering,
However, I've just made a PR that upgrades the decompiling tool to avoid any issues in the future, let me know if works
Thanks!
